package com.crudzaso.TinyTasks.model;

/**
 * Domain model representing a task.
 * Contains task identifier, description, and completion status.
 */
public class Todo {

    /** Unique identifier, auto-generated by repository */
    private int id;

    /** Task description */
    private String title;

    /** Completion status (true = done, false = pending) */
    private boolean done;

    /**
     * Default constructor for JSON deserialization.
     */
    public Todo() {
    }

    /**
     * Creates a new pending task with the specified title.
     *
     * @param title the task description
     */
    public Todo(String title){
        this.title = title;
        this.done = false;
    }

    /**
     * Creates a task with all fields (used for testing).
     *
     * @param id the task identifier
     * @param title the task description
     * @param done the completion status
     */
    public Todo(int id, String title, boolean done) {
        this.id = id;
        this.title = title;
        this.done = done;
    }

    /**
     * Gets the task identifier.
     *
     * @return the task ID
     */
    public int getId() {
        return id;
    }

    /**
     * Sets the task identifier.
     *
     * @param id the task ID
     */
    public void setId(int id) {
        this.id = id;
    }

    /**
     * Gets the task description.
     *
     * @return the task title
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the task description.
     *
     * @param title the task title
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * Checks if the task is completed.
     *
     * @return true if completed, false otherwise
     */
    public boolean isDone() {
        return done;
    }

    /**
     * Sets the completion status.
     *
     * @param done true for completed, false for pending
     */
    public void setDone(boolean done) {
        this.done = done;
    }

    @Override
    public String toString() {
        return "Todo{" +
                "id=" + id +
                ", title='" + title + '\'' +
                ", done=" + done +
                '}';
    }

}
